name: Deploy to Azure Devops
on: 
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched
      - name: Mirror to Azure DevOps
        env:
          AZURE_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git remote add azure https://saurabhbhargavofficial:${AZURE_PAT}@dev.azure.com/saurabhbhargavofficial/nodejsrepo/_git/nodejsrepo
          # Use the PAT in the URL (or set up git credentials via config)
          git push azure --mirror
  
