name: Deploy via Bastion Host

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key for Bastion
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BASTION_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into Bastion Host and Deploy to Main Server
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.BASTION_HOST }} << 'EOF'
            ssh-keyscan -H 172.31.2.123 >> ~/.ssh/known_hosts
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/demo.pem ubuntu@172.31.2.123 << 'INNER_SSH'
              cd /home/ubuntu/node-mssql
              git stash
              git pull origin main
              pm2 restart 0
            INNER_SSH
          EOF
